### ISSUE TITLE
Found a site where the add-on makes scrolling impossible

### ISSUE THREAD

**Issue by qoheniac** [quinton-ashley/firefox-hide-scrollbars#13]
It's this one: https://banking.ing-diba.de

**Comment by quinton-ashley** [comment]
@hensm hi again, I can't figure out what the compatibility issue is with this site.  Would you mind taking a look?

**Comment by hensm** [comment]
Can't reproduce.

**Comment by qoheniac** [comment]
I used Firefox 60.0.2.

**Comment by quinton-ashley** [comment]
hmm I found that on macOS and Windows versions of Firefox that site wouldn't scroll with the extension enabled.

**Comment by qoheniac** [comment]
I used the Linux version and it also didn't scroll.

**Comment by hensm** [comment]
Not sure there's a good solution for this one. Sites expect `<html>` to be the scrolling element, and the way this extension works breaks some of those expectations. It doesn't matter for most sites, but this one does some weird stuff that conflicts.

Possibly this:

````css
body > * {
  overflow: initial !important;
}
````

Though, I think that's highly likely to cause collateral damage.

For that specific site:
````css
.off-canvas-wrap {
    overflow: initial !important;
}
````
